FROM pytorch/pytorch:latest

COPY requirements.txt /temp/requirements.txt
COPY spell_it_app /spell_it_app
WORKDIR /spell_it_app
EXPOSE 8000

RUN apt update
RUN apt install -y postgresql-client
# RUN apt install postgresql-client build-base postgresql-dev git

RUN pip install -v -r /temp/requirements.txt

RUN adduser --disabled-password default-user

USER default-user