services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./spell_it_app:/spell_it_app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database

  database:
   image: postgres:14-alpine
   environment:
     - POSTGRES_DB=${DB_NAME}
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASS}

  redis:
    image: redis:7.0.12-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./spell_it_app:/spell_it_app
    # "links = Legacy feature" https://docs.docker.com/compose/compose-file/compose-file-v3/#links 
    links:
      - redis
    depends_on:
      - redis