FROM pytorch/pytorch:latest

COPY pip-requirements/requirements-worker.txt /temp/requirements-worker.txt
COPY spell_it_app /spell_it_app
WORKDIR /spell_it_app
EXPOSE 8000

RUN apt update
RUN apt install -y postgresql-client git
# RUN apt install postgresql-client build-base postgresql-dev git

RUN pip install -v -r /temp/requirements-worker.txt

RUN adduser --disabled-password default-user

USER default-user