FROM pytorch/pytorch:latest
COPY pip-requirements/requirements-worker-nix.txt /temp/requirements.txt
COPY spell_it_app /spell_it_app
WORKDIR /spell_it_app
EXPOSE 8000

RUN apt update
RUN apt install -y postgresql-client git espeak
#RUN mkdir /spell_it_app/nix-tts
#RUN git clone https://github.com/rendchevi/nix-tts.git /spell_it_app/nix-tts

RUN pip install -v -r /temp/requirements.txt

#RUN mv nix-tts/nix .


RUN adduser --disabled-password default-user

USER default-user